openapi: 3.0.0
info:
  title: Session API
  version: "0.1"
paths:
  /sessions:
    post:
      summary: Create a training session with exercises and notes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionWrite'
      responses:
        '201':
          description: Session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
  /sessions/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
    get:
      summary: Fetch a session by id
      responses:
        '200':
          description: Session found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '404':
          description: Session not found
    put:
      summary: Update a session, replacing exercises and notes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionWrite'
      responses:
        '200':
          description: Session updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '400':
          description: Validation failed (e.g., missing date or exercise metrics)
        '404':
          description: Session not found

components:
  schemas:
    Session:
      type: object
      required: [id, date, exercises, createdAt, updatedAt]
      properties:
        id:
          type: string
        date:
          type: string
          format: date
        startTime:
          type: string
          format: time
          nullable: true
        endTime:
          type: string
          format: time
          nullable: true
        durationMinutes:
          type: number
          nullable: true
        location:
          type: string
          nullable: true
        intensity:
          type: string
          nullable: true
        participants:
          type: array
          items:
            type: string
          nullable: true
        notes:
          type: string
          nullable: true
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/ExerciseEntry'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    SessionWrite:
      allOf:
        - $ref: '#/components/schemas/Session'
      required: [date, exercises]
      properties:
        id:
          readOnly: true
        createdAt:
          readOnly: true
        updatedAt:
          readOnly: true
    ExerciseEntry:
      type: object
      required: [id, name, order]
      properties:
        id:
          type: string
        sessionId:
          type: string
          nullable: true
        name:
          type: string
        sets:
          type: integer
          nullable: true
        reps:
          type: integer
          nullable: true
        load:
          type: number
          nullable: true
        durationSeconds:
          type: integer
          nullable: true
        restSeconds:
          type: integer
          nullable: true
        order:
          type: integer
        notes:
          type: string
          nullable: true
      oneOf:
        - required: [sets, reps]
        - required: [durationSeconds]
