openapi: 3.0.0
info:
  title: Landing Page Metrics API
  version: "0.1.0"
paths:
  /clients/{clientId}/metrics/completion:
    get:
      summary: Get recent completion metrics for a client
      parameters:
        - in: path
          name: clientId
          required: true
          schema:
            type: string
        - in: query
          name: weeks
          required: false
          description: Number of weeks to include (default 4, max 12)
          schema:
            type: integer
            minimum: 1
            maximum: 12
      responses:
        "200":
          description: Completion metrics for recent weeks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MetricSnapshot"
        "404":
          description: Client not found
        "500":
          description: Unexpected error

components:
  schemas:
    MetricSample:
      type: object
      required: [weekStart, sessionsScheduled, sessionsCompleted]
      properties:
        weekStart:
          type: string
          format: date
          description: Monday of the week in client local date
        sessionsScheduled:
          type: integer
          minimum: 0
        sessionsCompleted:
          type: integer
          minimum: 0
        volume:
          type: number
          description: Optional total volume for the week
        unit:
          type: string
          description: Unit for volume (e.g., minutes, km)
    MetricSnapshot:
      type: object
      required: [rangeLabel, hasData, samples]
      properties:
        rangeLabel:
          type: string
        completionRate:
          type: number
          format: float
          minimum: 0
          maximum: 1
        volume:
          type: number
          description: Aggregated volume for the window
        unit:
          type: string
        samples:
          type: array
          items:
            $ref: "#/components/schemas/MetricSample"
        hasData:
          type: boolean
